name: Semgrep SAST

on:
  push:
    branches: [ "master", "main" ]

jobs:
  semgrep:
    name: Scan Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep scan --config auto
